apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany 
  resources:
    requests:
      storage: 2Gi
  storageClassName: /srv/app- data