apiVersion: v1
kind: pod
metadata:
  name: mypod
spec:
  containers:
  - name: nginx 
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: redis
    image: nginx:1.14.2
    ports:
    - containerPort: 80